// pokemon-mapper.js — speciesId -> image URL mapping

const ARTWORK_BASE = 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork';

// Pre-built map: PVPoke speciesId suffix -> PokeAPI dex ID
// Generated by tools/build-form-map.js cross-referencing PVPoke + PokeAPI
// Covers Alolan, Galarian, Hisuian, Paldean, Mega, and special forms
const FORM_ID_MAP = {
  // Alolan forms (10001+)
  'rattata_alolan': 10091,
  'raticate_alolan': 10092,
  'raichu_alolan': 10100,
  'sandshrew_alolan': 10101,
  'sandslash_alolan': 10102,
  'vulpix_alolan': 10103,
  'ninetales_alolan': 10104,
  'diglett_alolan': 10105,
  'dugtrio_alolan': 10106,
  'meowth_alolan': 10107,
  'persian_alolan': 10108,
  'geodude_alolan': 10109,
  'graveler_alolan': 10110,
  'golem_alolan': 10111,
  'grimer_alolan': 10112,
  'muk_alolan': 10113,
  'exeggutor_alolan': 10114,
  'marowak_alolan': 10115,

  // Galarian forms
  'meowth_galarian': 10158,
  'ponyta_galarian': 10159,
  'rapidash_galarian': 10160,
  'slowpoke_galarian': 10161,
  'slowbro_galarian': 10162,
  'farfetchd_galarian': 10163,
  'weezing_galarian': 10164,
  'mr_mime_galarian': 10165,
  'articuno_galarian': 10166,
  'zapdos_galarian': 10167,
  'moltres_galarian': 10168,
  'slowking_galarian': 10169,
  'corsola_galarian': 10170,
  'zigzagoon_galarian': 10171,
  'linoone_galarian': 10172,
  'darumaka_galarian': 10173,
  'darmanitan_galarian': 10174,
  'darmanitan_galarian_zen': 10175,
  'yamask_galarian': 10176,
  'stunfisk_galarian': 10177,

  // Hisuian forms
  'growlithe_hisuian': 10229,
  'arcanine_hisuian': 10230,
  'voltorb_hisuian': 10231,
  'electrode_hisuian': 10232,
  'typhlosion_hisuian': 10233,
  'qwilfish_hisuian': 10234,
  'sneasel_hisuian': 10235,
  'samurott_hisuian': 10236,
  'lilligant_hisuian': 10237,
  'zorua_hisuian': 10238,
  'zoroark_hisuian': 10239,
  'braviary_hisuian': 10240,
  'sliggoo_hisuian': 10241,
  'goodra_hisuian': 10242,
  'avalugg_hisuian': 10243,
  'decidueye_hisuian': 10244,

  // Paldean forms
  'tauros_paldean_combat': 10250,
  'tauros_paldean_blaze': 10251,
  'tauros_paldean_aqua': 10252,
  'wooper_paldean': 10253,

  // Mega evolutions
  'venusaur_mega': 10033,
  'charizard_mega_x': 10034,
  'charizard_mega_y': 10035,
  'blastoise_mega': 10036,
  'beedrill_mega': 10090,
  'pidgeot_mega': 10073,
  'alakazam_mega': 10037,
  'slowbro_mega': 10071,
  'gengar_mega': 10038,
  'kangaskhan_mega': 10039,
  'pinsir_mega': 10040,
  'gyarados_mega': 10041,
  'aerodactyl_mega': 10042,
  'mewtwo_mega_x': 10043,
  'mewtwo_mega_y': 10044,
  'ampharos_mega': 10045,
  'steelix_mega': 10072,
  'scizor_mega': 10046,
  'heracross_mega': 10047,
  'houndoom_mega': 10048,
  'tyranitar_mega': 10049,
  'sceptile_mega': 10065,
  'blaziken_mega': 10050,
  'swampert_mega': 10064,
  'gardevoir_mega': 10051,
  'sableye_mega': 10066,
  'mawile_mega': 10052,
  'aggron_mega': 10053,
  'medicham_mega': 10054,
  'manectric_mega': 10055,
  'sharpedo_mega': 10070,
  'camerupt_mega': 10069,
  'altaria_mega': 10067,
  'banette_mega': 10056,
  'absol_mega': 10057,
  'glalie_mega': 10074,
  'salamence_mega': 10089,
  'metagross_mega': 10058,
  'latias_mega': 10062,
  'latios_mega': 10063,
  'rayquaza_mega': 10079,
  'lopunny_mega': 10088,
  'garchomp_mega': 10058,
  'lucario_mega': 10059,
  'abomasnow_mega': 10060,
  'gallade_mega': 10068,
  'audino_mega': 10061,
  'diancie_mega': 10075,
  'gyarados_mega': 10041,

  // Primal forms
  'groudon_primal': 10078,
  'kyogre_primal': 10077,

  // Other special forms
  'castform_sunny': 10013,
  'castform_rainy': 10014,
  'castform_snowy': 10015,
  'deoxys_attack': 10001,
  'deoxys_defense': 10002,
  'deoxys_speed': 10003,
  'wormadam_sandy': 10004,
  'wormadam_trash': 10005,
  'cherrim_sunny': 10006,
  'giratina_origin': 10007,
  'shaymin_sky': 10008,
  'basculin_blue_striped': 10016,
  'darmanitan_zen': 10017,
  'tornadus_therian': 10019,
  'thundurus_therian': 10020,
  'landorus_therian': 10021,
  'kyurem_black': 10022,
  'kyurem_white': 10023,
  'keldeo_resolute': 10024,
  'meloetta_pirouette': 10018,
  'aegislash_blade': 10026,
  'pumpkaboo_small': 10027,
  'pumpkaboo_large': 10028,
  'pumpkaboo_super': 10029,
  'gourgeist_small': 10030,
  'gourgeist_large': 10031,
  'gourgeist_super': 10032,
  'hoopa_unbound': 10086,
  'lycanroc_midnight': 10126,
  'lycanroc_dusk': 10152,
  'wishiwashi_school': 10127,
  'oricorio_pom_pom': 10123,
  'oricorio_pau': 10124,
  'oricorio_sensu': 10125,
  'meowstic_female': 10025,
  'indeedee_female': 10178,
  'zacian_crowned': 10188,
  'zamazenta_crowned': 10189,
  'urshifu_rapid_strike': 10191,
  'calyrex_ice': 10193,
  'calyrex_shadow': 10194,
  'enamorus_therian': 10249,
  'basculegion_female': 10248,
  'oinkologne_female': 10254,
  'maushold_family_of_three': 10256,
  'squawkabilly_blue': 10258,
  'squawkabilly_yellow': 10259,
  'squawkabilly_white': 10260,
  'palafin_hero': 10261,
  'tatsugiri_droopy': 10262,
  'tatsugiri_stretchy': 10263,
  'dudunsparce_three_segment': 10264,
  'gimmighoul_roaming': 10265,
  'ogerpon_wellspring': 10273,
  'ogerpon_hearthflame': 10274,
  'ogerpon_cornerstone': 10275,
};

// Special base-name Pokemon where PVPoke uses underscores but dex name has hyphens or different format
const SPECIAL_NAMES = {
  'mr_mime': 122,
  'mr_rime': 866,
  'mime_jr': 439,
  'ho_oh': 250,
  'porygon_z': 474,
  'tapu_koko': 785,
  'tapu_lele': 786,
  'tapu_bulu': 787,
  'tapu_fini': 788,
  'type_null': 772,
  'jangmo_o': 782,
  'hakamo_o': 783,
  'kommo_o': 784,
  'nidoran_female': 29,
  'nidoran_male': 32,
  'farfetchd': 83,
  'sirfetchd': 865,
  'flabebe': 669,
  'great_tusk': 984,
  'scream_tail': 985,
  'brute_bonnet': 986,
  'flutter_mane': 987,
  'slither_wing': 988,
  'sandy_shocks': 989,
  'iron_treads': 990,
  'iron_bundle': 991,
  'iron_hands': 992,
  'iron_juggernaut': 993,
  'iron_moth': 994,
  'iron_thorns': 995,
  'roaring_moon': 1005,
  'iron_valiant': 1006,
  'walking_wake': 1009,
  'iron_leaves': 1010,
  'gouging_fire': 1020,
  'raging_bolt': 1021,
  'iron_boulder': 1022,
  'iron_crown': 1023,
  'wo_chien': 1001,
  'chien_pao': 1002,
  'ting_lu': 1003,
  'chi_yu': 1004,
};

/**
 * Get the PokeAPI artwork URL for a PVPoke speciesId.
 * @param {string} speciesId - PVPoke species ID (e.g., "ninetales_alolan", "sableye_shadow")
 * @param {Map} pokemonMap - Map of speciesId -> gamemaster data (for dex number fallback)
 * @returns {string} URL to the official artwork PNG
 */
export function getImageUrl(speciesId, pokemonMap) {
  // Strip shadow suffix — shadow forms look the same
  let cleanId = speciesId.replace(/_shadow$/, '');

  // Check form map first (alternate forms)
  if (FORM_ID_MAP[cleanId]) {
    return `${ARTWORK_BASE}/${FORM_ID_MAP[cleanId]}.png`;
  }

  // Check special names
  if (SPECIAL_NAMES[cleanId]) {
    return `${ARTWORK_BASE}/${SPECIAL_NAMES[cleanId]}.png`;
  }

  // Check if it's a special name with a suffix (e.g., mr_mime_galarian)
  for (const [name, dex] of Object.entries(SPECIAL_NAMES)) {
    if (cleanId.startsWith(name + '_')) {
      const suffix = cleanId.slice(name.length);
      const formKey = name + suffix;
      if (FORM_ID_MAP[formKey]) {
        return `${ARTWORK_BASE}/${FORM_ID_MAP[formKey]}.png`;
      }
    }
  }

  // Fallback: use dex number from gamemaster
  const pokeData = pokemonMap?.get(speciesId) || pokemonMap?.get(cleanId);
  if (pokeData && pokeData.dex) {
    return `${ARTWORK_BASE}/${pokeData.dex}.png`;
  }

  // Last resort: try to find base form in map
  const baseName = cleanId.split('_')[0];
  const baseData = pokemonMap?.get(baseName);
  if (baseData && baseData.dex) {
    return `${ARTWORK_BASE}/${baseData.dex}.png`;
  }

  // Placeholder
  return '';
}

/**
 * Get display name from speciesId
 */
export function getDisplayName(speciesId, pokemonMap) {
  const pokeData = pokemonMap?.get(speciesId);
  if (pokeData && pokeData.speciesName) {
    return pokeData.speciesName;
  }
  // Fallback: format the speciesId nicely
  return speciesId
    .split('_')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
}
